export const INVALIDATE_PAYMENT_RECEIPTS = 'INVALIDATE_PAYMENT_RECEIPTS';
export const REQUEST_PAYMENT_RECEIPTS = 'REQUEST_PAYMENT_RECEIPTS';
export const RECEIVE_PAYMENT_RECEIPTS = 'RECEIVE_PAYMENT_RECEIPTS';
export const FAILURE_FETCH_PAYMENT_RECEIPTS = 'FAILURE_FETCH_PAYMENT_RECEIPTS';
export const POST_PAYMENT_RECEIPT = 'POST_PAYMENT_RECEIPT';
export const ADD_PAYMENT_RECEIPT = 'ADD_PAYMENT_RECEIPT';
export const EDIT_PAYMENT_RECEIPT = 'EDIT_PAYMENT_RECEIPT';
export const DELETE_PAYMENT_RECEIPT = 'DELETE_PAYMENT_RECEIPT';

export const INVALIDATE_SERVICES = 'INVALIDATE_SERVICES';
export const REQUEST_SERVICES = 'REQUEST_SERVICES';
export const RECEIVE_SERVICES = 'RECEIVE_SERVICES';
export const FAILURE_FETCH_SERVICES = 'FAILURE_FETCH_SERVICES';

export const INVALIDATE_ORGANIZATION_INFOS = 'INVALIDATE_ORGANIZATION_INFOS';
export const REQUEST_ORGANIZATION_INFOS = 'REQUEST_ORGANIZATION_INFOS';
export const RECEIVE_ORGANIZATION_INFOS = 'RECEIVE_ORGANIZATION_INFOS';
export const FAILURE_FETCH_ORGANIZATION_INFOS = 'FAILURE_FETCH_ORGANIZATION_INFOS';